use-grammars = { only = ["clap"] }

[[language]]
name = "clap"
scope = "source.clap"
file-types = ["clap"]
comment-token = "--"
language-servers = ["clap"]
grammar = "clap"
roots = ["clap.cabal"]
formatter = { command = "/home/mewhhaha/src/clapse/artifacts/bin/clap", args = ["format", "--stdin"] }

[[grammar]]
name = "clap"
source = { path = "/home/mewhhaha/src/clapse/tree-sitter-clap" }

[language-server.clap]
command = "/home/mewhhaha/src/clapse/artifacts/bin/clap"
args = ["lsp", "--stdio"]
