export declare function CommandCompile(): number;
export declare function CommandFormat(): number;
export declare function CommandSelfhost(): number;
export declare function CommandUnknown(): number;
export declare function CompileRequestMissingPath(): number;
export declare function CompileRequestMissingSource(): number;
export declare function CompileRequestReady(): number;
export declare function Just(arg0: number): number;
export declare function Nothing(): number;
export declare function CBool(arg0: number): number;
export declare function CVar(arg0: number): number;
export declare function CNot(arg0: number): number;
export declare function CAnd(arg0: number, arg1: number): number;
export declare function COr(arg0: number, arg1: number): number;
export declare function kernel_class_dispatch(): number;
export declare function class_dispatch_default_resolved(): number;
export declare function resolve_class_method(arg0: number, arg1: number, arg2: number): number;
export declare function rewrite_bool_law_expr(arg0: number): number;
export declare function apply_class_law_rewrites(arg0: number, arg1: number): number;
export declare function derive_class_method_with_dispatch(arg0: number, arg1: number, arg2: number): number;
export declare function derive_class_method(arg0: number, arg1: number): number;
export declare function derive_law_expr_with_dispatch(arg0: number, arg1: number): number;
export declare function derive_law_expr(arg0: number): number;
export declare function derive_instance_method_with_dispatch(arg0: number, arg1: number, arg2: number): number;
export declare function derive_instance_method(arg0: number, arg1: number): number;
export declare function class_rewrite_pipeline(arg0: number, arg1: number, arg2: number): number;
export declare function class_rewrite_pipeline_default(arg0: number, arg1: number, arg2: number): number;
export declare function class_rewrite_pipeline_applicative(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function class_rewrite_pipeline_static(arg0: number, arg1: number): number;
export declare function EscapeLifetimeLocal(): number;
export declare function EscapeLifetimeEscaped(): number;
export declare function EscapeLifetimeUnknown(): number;
export declare function OwnershipRewriteLinear(): number;
export declare function OwnershipRewriteCopyOnWrite(): number;
export declare function SliceWriteAliasSingleUse(): number;
export declare function SliceWriteAliasSharedOrEscaped(): number;
export declare function SliceWriteAliasUnknown(): number;
export declare function SliceSetU8WriteChainContext(arg0: number, arg1: number, arg2: number): number;
export declare function SliceSetU8WriteChainHint(): number;
export declare function MemoryPassEscapeLifetimeAnnotation(): number;
export declare function MemoryPassSliceOwnershipRewrite(): number;
export declare function collapse_pipeline_stages(): number;
export declare function collapse_pipeline_escape_lifetime(arg0: number): number;
export declare function collapse_pipeline_slice_ownership_rewrite(arg0: number): number;
export declare function slice_set_u8_has_literal(arg0: number, arg1: number): number;
export declare function slice_set_u8_request_scope(arg0: number): number;
export declare function slice_set_u8_request_chain_hint(arg0: number): number;
export declare function slice_set_u8_chain_hint_to_context(arg0: number): number;
export declare function slice_set_u8_chain_policy(arg0: number): number;
export declare function collapse_pipeline_slice_write_policy(arg0: number): number;
export declare function slice_set_u8_base_context(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function slice_set_u8_context_with_alias(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function slice_set_u8_context_with_freeze(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function slice_set_u8_rewrite_mode(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function slice_set_u8_context_mode(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function slice_set_u8_context_mode_with_policy(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function collapse_pipeline_run(arg0: number): number;
export declare function slice_set_u8_write(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function slice_set_u8_cow(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function slice_set_u8_rewrite(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function min2(arg0: number, arg1: number): number;
export declare function json_error_prefix(): number;
export declare function json_error_suffix(): number;
export declare function json_format_prefix(): number;
export declare function json_format_suffix(): number;
export declare function json_selfhost_prefix(): number;
export declare function json_selfhost_suffix(): number;
export declare function json_selfhost_ok(): number;
export declare function json_unknown_error(): number;
export declare function copy_slice_literal(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function json_compile_error_byte(arg0: number): number;
export declare function json_error_prefix_byte(arg0: number): number;
export declare function json_error_suffix_byte(arg0: number): number;
export declare function json_format_prefix_byte(arg0: number): number;
export declare function json_format_suffix_byte(arg0: number): number;
export declare function json_selfhost_prefix_byte(arg0: number): number;
export declare function json_selfhost_suffix_byte(arg0: number): number;
export declare function json_selfhost_ok_byte(arg0: number): number;
export declare function json_unknown_error_byte(arg0: number): number;
export declare function fill_json_compile_error(arg0: number, arg1: number, arg2: number): number;
export declare function fill_json_error_prefix(arg0: number, arg1: number, arg2: number): number;
export declare function fill_json_error_suffix(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function fill_json_format_prefix(arg0: number, arg1: number, arg2: number): number;
export declare function fill_json_format_suffix(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function fill_json_selfhost_prefix(arg0: number, arg1: number, arg2: number): number;
export declare function fill_json_selfhost_suffix(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function fill_json_selfhost_ok(arg0: number, arg1: number, arg2: number): number;
export declare function fill_json_unknown_error(arg0: number, arg1: number, arg2: number): number;
export declare function error_response_from_message(arg0: number, arg1: number, arg2: number): number;
export declare function compile_not_implemented_response(arg0: number, arg1: number, arg2: number): number;
export declare function compile_missing_input_path_response(arg0: number, arg1: number, arg2: number): number;
export declare function compile_missing_input_source_response(arg0: number, arg1: number, arg2: number): number;
export declare function compile_error_response(arg0: number, arg1: number): number;
export declare function compile_stub_success_response(arg0: number, arg1: number, arg2: number): number;
export declare function compile_source_start(arg0: number, arg1: number): number;
export declare function compile_request_tag(arg0: number, arg1: number): number;
export declare function input_path_end_for_request(arg0: number, arg1: number, arg2: number): number;
export declare function source_end_for_request(arg0: number, arg1: number, arg2: number): number;
export declare function matches_literal_at(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function find_literal_start(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function find_literal_start_step(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function find_compile_mode_start(arg0: number, arg1: number): number;
export declare function is_compile_mode_literal(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function is_compile_mode_literal_match(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function is_compile_mode_stub_success(arg0: number, arg1: number): number;
export declare function compile_response(arg0: number, arg1: number): number;
export declare function is_space_byte(arg0: number): number;
export declare function skip_ws(arg0: number, arg1: number, arg2: number): number;
export declare function skip_ws_step(arg0: number, arg1: number, arg2: number): number;
export declare function source_value_start_at(arg0: number, arg1: number, arg2: number): number;
export declare function source_value_start_at_colon(arg0: number, arg1: number, arg2: number): number;
export declare function source_value_start_at_quote(arg0: number, arg1: number, arg2: number): number;
export declare function source_value_start_at_quote_check(arg0: number, arg1: number, arg2: number): number;
export declare function find_json_key_value_start(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function parse_json_key_value_end(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function parse_json_key_value_end_to_start(arg0: number, arg1: number, arg2: number): number;
export declare function find_source_start(arg0: number, arg1: number, arg2: number): number;
export declare function find_input_source_start(arg0: number, arg1: number, arg2: number): number;
export declare function find_input_path_start(arg0: number, arg1: number, arg2: number): number;
export declare function max_source_scan_steps(): number;
export declare function max_inline_request_len(): number;
export declare function max_inline_validation_request_len(): number;
export declare function find_source_end(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function find_source_end_limited(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function find_source_end_limited_step(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function find_source_end_limited_quote(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function copy_slice_segment(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number): number;
export declare function json_escape_extra_len(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function json_copy_escaped_segment(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number, arg7: number): number;
export declare function json_response_with_literal_prefix_suffix(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function json_response_with_slice_segment(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): number;
export declare function json_response_with_escaped_slice_segment(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number, arg5: number, arg6: number): number;
export declare function json_response_from_slice(arg0: number, arg1: number, arg2: number): number;
export declare function json_slice_end(arg0: number, arg1: number, arg2: number): number;
export declare function format_empty_response(arg0: number, arg1: number): number;
export declare function format_source_response(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function format_ok_response(arg0: number, arg1: number): number;
export declare function selfhost_empty_response(arg0: number, arg1: number): number;
export declare function selfhost_source_response(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function selfhost_ok_response_no_input_source(arg0: number, arg1: number, arg2: number): number;
export declare function selfhost_ok_response(arg0: number, arg1: number): number;
export declare function unknown_error_response(arg0: number, arg1: number): number;
export declare function is_command_literal(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function command_tag_code_compile(arg0: number): number;
export declare function command_tag_code_format(arg0: number): number;
export declare function command_tag_code_selfhost(arg0: number): number;
export declare function parse_command_tag(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function parse_command_tag_code(arg0: number, arg1: number, arg2: number): number;
export declare function command_tag_of(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function command_tag_at(arg0: number, arg1: number, arg2: number): number;
export declare function find_command_tag(arg0: number, arg1: number, arg2: number): number;
export declare function command_tag(arg0: number): number;
export declare function clapse_run(arg0: number): number;
