export declare function CommandCompile(): number;
export declare function CommandFormat(): number;
export declare function CommandSelfhost(): number;
export declare function Just(arg0: number): number;
export declare function Nothing(): number;
export declare function MonadicLineNil(): number;
export declare function ParsedLine(arg0: number, arg1: number): number;
export declare function ChainCollect(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function CBool(arg0: number): number;
export declare function CVar(arg0: number): number;
export declare function CNot(arg0: number): number;
export declare function CAnd(arg0: number, arg1: number): number;
export declare function COr(arg0: number, arg1: number): number;
export declare function kernel_class_dispatch(): number;
export declare function class_dispatch_default_resolved(): number;
export declare function resolve_class_method(arg0: number, arg1: number, arg2: number): number;
export declare function rewrite_bool_law_expr(arg0: number): number;
export declare function apply_class_law_rewrites(arg0: number, arg1: number): number;
export declare function derive_class_method_with_dispatch(arg0: number, arg1: number, arg2: number): number;
export declare function derive_class_method(arg0: number, arg1: number): number;
export declare function derive_law_expr_with_dispatch(arg0: number, arg1: number): number;
export declare function derive_law_expr(arg0: number): number;
export declare function derive_instance_method_with_dispatch(arg0: number, arg1: number, arg2: number): number;
export declare function derive_instance_method(arg0: number, arg1: number): number;
export declare function class_rewrite_pipeline(arg0: number, arg1: number, arg2: number): number;
export declare function class_rewrite_pipeline_default(arg0: number, arg1: number, arg2: number): number;
export declare function class_rewrite_pipeline_applicative(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function class_rewrite_pipeline_static(arg0: number, arg1: number): number;
export declare function EscapeLifetimeLocal(): number;
export declare function EscapeLifetimeEscaped(): number;
export declare function EscapeLifetimeUnknown(): number;
export declare function OwnershipRewriteLinear(): number;
export declare function OwnershipRewriteCopyOnWrite(): number;
export declare function SliceWriteAliasSingleUse(): number;
export declare function SliceWriteAliasSharedOrEscaped(): number;
export declare function SliceWriteAliasUnknown(): number;
export declare function SliceSetU8WriteChainContext(arg0: number, arg1: number, arg2: number): number;
export declare function SliceSetU8WriteChainHint(): number;
export declare function MemoryPassEscapeLifetimeAnnotation(): number;
export declare function MemoryPassSliceOwnershipRewrite(): number;
export declare function collapse_pipeline_stages(): number;
export declare function collapse_pipeline_escape_lifetime(arg0: number): number;
export declare function collapse_pipeline_slice_ownership_rewrite(arg0: number): number;
export declare function slice_set_u8_has_literal(arg0: number, arg1: number): number;
export declare function slice_set_u8_request_scope(arg0: number): number;
export declare function slice_set_u8_request_chain_hint(arg0: number): number;
export declare function slice_set_u8_chain_hint_to_context(arg0: number): number;
export declare function slice_set_u8_chain_policy(arg0: number): number;
export declare function collapse_pipeline_slice_write_policy(arg0: number): number;
export declare function slice_set_u8_base_context(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function slice_set_u8_context_with_alias(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function slice_set_u8_context_with_freeze(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function slice_set_u8_rewrite_mode(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function slice_set_u8_context_mode(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function slice_set_u8_context_mode_with_policy(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function collapse_pipeline_run(arg0: number): number;
export declare function slice_set_u8_write(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function slice_set_u8_cow(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function slice_set_u8_rewrite(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function min2(arg0: number, arg1: number): number;
export declare function matches_literal_at(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function find_literal_start(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function find_literal_start_step(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function is_compile_mode_literal(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function is_compile_mode_literal_match(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function is_command_literal(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function command_tag_code_compile(arg0: number): number;
export declare function command_tag_code_format(arg0: number): number;
export declare function command_tag_code_selfhost(arg0: number): number;
export declare function command_tag_code_lsp_symbol_index(arg0: number): number;
export declare function command_tag_code_lsp_hover(arg0: number): number;
export declare function command_tag_code_lsp_definition(arg0: number): number;
export declare function parse_command_tag(arg0: number, arg1: number, arg2: number, arg3: number): number;
export declare function parse_command_tag_code(arg0: number, arg1: number, arg2: number): number;
export declare function command_tag_of(arg0: number, arg1: number, arg2: number, arg3: number, arg4: number): number;
export declare function command_tag_at(arg0: number, arg1: number, arg2: number): number;
export declare function find_command_tag(arg0: number, arg1: number, arg2: number): number;
export declare function command_tag(arg0: number): number;
export declare function clapse_run(arg0: number): number;
